/* tslint:disable */
/* eslint-disable */
/**
 * 短链平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    no: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    allowRegion: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    banProxy: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    destLink: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    banLink: string;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'no': json['no'],
        'allowRegion': json['allow_region'],
        'banProxy': json['ban_proxy'],
        'destLink': json['dest_link'],
        'banLink': json['ban_link'],
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'no': value.no,
        'allow_region': value.allowRegion,
        'ban_proxy': value.banProxy,
        'dest_link': value.destLink,
        'ban_link': value.banLink,
    };
}


