/* tslint:disable */
/* eslint-disable */
/**
 * 短链平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200Data,
    InlineResponse200DataFromJSON,
    InlineResponse200DataFromJSONTyped,
    InlineResponse200DataToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    code: number;
    /**
     * 
     * @type {Array<InlineResponse200Data>}
     * @memberof InlineResponse200
     */
    data: Array<InlineResponse200Data>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    message: string;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': ((json['data'] as Array<any>).map(InlineResponse200DataFromJSON)),
        'message': json['message'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'data': ((value.data as Array<any>).map(InlineResponse200DataToJSON)),
        'message': value.message,
    };
}


