/* tslint:disable */
/* eslint-disable */
/**
 * 短链平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200Data
 */
export interface InlineResponse200Data {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200Data
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Data
     */
    no: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Data
     */
    allow_region: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200Data
     */
    ban_proxy: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Data
     */
    dest_link: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Data
     */
    ban_link: string;
}

export function InlineResponse200DataFromJSON(json: any): InlineResponse200Data {
    return InlineResponse200DataFromJSONTyped(json, false);
}

export function InlineResponse200DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200Data {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'no': json['no'],
        'allow_region': json['allow_region'],
        'ban_proxy': json['ban_proxy'],
        'dest_link': json['dest_link'],
        'ban_link': json['ban_link'],
    };
}

export function InlineResponse200DataToJSON(value?: InlineResponse200Data | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'no': value.no,
        'allow_region': value.allow_region,
        'ban_proxy': value.ban_proxy,
        'dest_link': value.dest_link,
        'ban_link': value.ban_link,
    };
}


