export default (initialState: { userinfo?: API.Userinfo }) => {
  let permissions: string[] = initialState.userinfo?.permissions || [];
  return {
    hasAdminRole: initialState.userinfo?.roles.includes('ADMIN'),
    SUPER_ADMIN: initialState.userinfo?.roles.includes('SUPER_ADMIN'),
    DATA__ALL: permissions.includes('DATA__ALL'),
    DATA__SELF: permissions.includes('DATA__SELF'),
    DATA__DEPT: permissions.includes('DATA__DEPT'),
    DATA__DEPT_AND_CHILD: permissions.includes('DATA__DEPT_AND_CHILD'),
    SHORT_LINK__VIEW: permissions.includes('SHORT_LINK__VIEW'),
    SHORT_LINK__EDIT: permissions.includes('SHORT_LINK__EDIT'),
    SHORT_LINK__DELETE: permissions.includes('SHORT_LINK__DELETE'),
    CLOAK__DELETE: permissions.includes('CLOAK__DELETE'),
    CLOAK__EDIT: permissions.includes('CLOAK__EDIT'),
    CLOAK__VIEW: permissions.includes('CLOAK__VIEW'),
    SHORT_LINK__FILTER: permissions.includes('SHORT_LINK__FILTER'),
    SHORT_LINK__ALL_DATA: permissions.includes('SHORT_LINK__ALL_DATA'),
    SETTING__VIEW: permissions.includes('SETTING__VIEW'),
    USER__VIEW: permissions.includes('USER__VIEW'),
    USER__EDIT: permissions.includes('USER__EDIT'),
    USER__DELETE: permissions.includes('USER__DELETE'),
    ROLE__VIEW: permissions.includes('ROLE__VIEW'),
    ROLE__EDIT: permissions.includes('ROLE__EDIT'),
    ROLE__DELETE: permissions.includes('ROLE__DELETE'),
    DOMAIN__VIEW: permissions.includes('DOMAIN__VIEW'),
    DOMAIN__EDIT: permissions.includes('DOMAIN__EDIT'),
    DOMAIN__DELETE: permissions.includes('DOMAIN__DELETE'),
    SERVER__VIEW: permissions.includes('SERVER__VIEW'),
    SERVER__EDIT: permissions.includes('SERVER__EDIT'),
    SERVER__DELETE: permissions.includes('SERVER__DELETE'),
    LANDING__VIEW: permissions.includes('LANDING__VIEW'),
    LANDING__EDIT: permissions.includes('LANDING__EDIT'),
    LANDING__DELETE: permissions.includes('LANDING__DELETE'),
    ORDER__VIEW: permissions.includes('ORDER__VIEW'),
    ORDER__EDIT: permissions.includes('ORDER__EDIT'),
    ORDER__DELETE: permissions.includes('ORDER__DELETE'),
    WEBSITE__VIEW: permissions.includes('WEBSITE__VIEW'),
    WEBSITE__EDIT: permissions.includes('WEBSITE__EDIT'),
    WEBSITE__DELETE: permissions.includes('WEBSITE__DELETE'),
    ORDER_GROUP__VIEW: permissions.includes('ORDER_GROUP__VIEW'),
    ORDER_GROUP__EDIT: permissions.includes('ORDER_GROUP__EDIT'),
    ORDER_GROUP__DELETE: permissions.includes('ORDER_GROUP__DELETE'),
    // COMMODITY_GROUP_PERMISSIONS 商品组
    COMMODITY_GROUP__VIEW: permissions.includes('COMMODITY_GROUP__VIEW'),
    COMMODITY_GROUP__EDIT: permissions.includes('COMMODITY_GROUP__EDIT'),
    COMMODITY_GROUP__DELETE: permissions.includes('COMMODITY_GROUP__DELETE'),
    // COMMODITY_PERMISSIONS 商品
    COMMODITY__VIEW: permissions.includes('COMMODITY__VIEW'),
    COMMODITY__EDIT: permissions.includes('COMMODITY__EDIT'),
    COMMODITY__DELETE: permissions.includes('COMMODITY__DELETE'),
    // SYS_ORDER_PERMISSIONS 系统订单
    SYS_ORDER__VIEW: permissions.includes('SYS_ORDER__VIEW'),
    SYS_ORDER__EDIT: permissions.includes('SYS_ORDER__EDIT'),
    SYS_ORDER__DELETE: permissions.includes('SYS_ORDER__DELETE'),
      // COMMODITY_ITEM_PERMISSIONS 库存
    COMMODITY_ITEM__VIEW: permissions.includes('COMMODITY_ITEM__VIEW'),
    COMMODITY_ITEM__EDIT: permissions.includes('COMMODITY_ITEM__EDIT'),
    COMMODITY_ITEM__DELETE: permissions.includes('COMMODITY_ITEM__DELETE'),
  };
};
